name: SimpleJoinMessageAI
version: '0.0.2-SNAPSHOT'
main: io.github.planethouki.SimpleJoinMessageAI
api-version: '1.21'
commands:
  sjm:
    description: "SimpleJoinMessageAI command"
    permission: "simplejoinmessage.command.sjm"
permissions:
  simplejoinmessage.command.sjm:
    description: "Allows the player to use the /sjm command"
    default: op
