name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: shadowJar

#      - name: Archive build artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: plugin-jar
#          path: build/libs/*.jar
